print("Welcome to the Simple Calculator!")
print("This calculator takes two user supplied numbers and divides them.")
NUM1=int(input("Enter the first number: "))
NUM2=int(input("Enter the Second number: "))
print(NUM1/NUM2)
